name: sewa_model
description: Models for SEWA project, including user, product, order, etc.
version: 0.0.2
homepage: https://github.com/rvndsngwn/sewa_model.git

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  freezed:

flutter:
